version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    command: ["npx", "nodemon", "server"]
    volumes:
      - ./:/usr/src/app
